// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package tcp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTcp returns the embedded CollectionSpec for tcp.
func loadTcp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcp: %w", err)
	}

	return spec, err
}

// loadTcpObjects loads tcp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpObjects
//	*tcpPrograms
//	*tcpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpSpecs struct {
	tcpProgramSpecs
	tcpMapSpecs
	tcpVariableSpecs
}

// tcpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpProgramSpecs struct {
	HandleAccept    *ebpf.ProgramSpec `ebpf:"handle_accept"`
	HandleClose     *ebpf.ProgramSpec `ebpf:"handle_close"`
	HandleConnectV4 *ebpf.ProgramSpec `ebpf:"handle_connect_v4"`
	HandleConnectV6 *ebpf.ProgramSpec `ebpf:"handle_connect_v6"`
}

// tcpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpMapSpecs struct {
	Events       *ebpf.MapSpec `ebpf:"events"`
	TargetCgroup *ebpf.MapSpec `ebpf:"target_cgroup"`
}

// tcpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpVariableSpecs struct {
}

// tcpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpObjects struct {
	tcpPrograms
	tcpMaps
	tcpVariables
}

func (o *tcpObjects) Close() error {
	return _TcpClose(
		&o.tcpPrograms,
		&o.tcpMaps,
	)
}

// tcpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpMaps struct {
	Events       *ebpf.Map `ebpf:"events"`
	TargetCgroup *ebpf.Map `ebpf:"target_cgroup"`
}

func (m *tcpMaps) Close() error {
	return _TcpClose(
		m.Events,
		m.TargetCgroup,
	)
}

// tcpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpVariables struct {
}

// tcpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpPrograms struct {
	HandleAccept    *ebpf.Program `ebpf:"handle_accept"`
	HandleClose     *ebpf.Program `ebpf:"handle_close"`
	HandleConnectV4 *ebpf.Program `ebpf:"handle_connect_v4"`
	HandleConnectV6 *ebpf.Program `ebpf:"handle_connect_v6"`
}

func (p *tcpPrograms) Close() error {
	return _TcpClose(
		p.HandleAccept,
		p.HandleClose,
		p.HandleConnectV4,
		p.HandleConnectV6,
	)
}

func _TcpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcp_bpfeb.o
var _TcpBytes []byte
