// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package profile

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type profileCountKey struct {
	_           structs.HostLayout
	Tgid        uint32
	KernStackId int32
	UserStackId int32
	Comm        [16]int8
}

// loadProfile returns the embedded CollectionSpec for profile.
func loadProfile() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProfileBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load profile: %w", err)
	}

	return spec, err
}

// loadProfileObjects loads profile and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*profileObjects
//	*profilePrograms
//	*profileMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProfileObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProfile()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// profileSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type profileSpecs struct {
	profileProgramSpecs
	profileMapSpecs
	profileVariableSpecs
}

// profileProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type profileProgramSpecs struct {
	HandleSample *ebpf.ProgramSpec `ebpf:"handle_sample"`
}

// profileMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type profileMapSpecs struct {
	AgentPidns   *ebpf.MapSpec `ebpf:"agent_pidns"`
	Counts       *ebpf.MapSpec `ebpf:"counts"`
	Stacks       *ebpf.MapSpec `ebpf:"stacks"`
	TargetCgroup *ebpf.MapSpec `ebpf:"target_cgroup"`
}

// profileVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type profileVariableSpecs struct {
}

// profileObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProfileObjects or ebpf.CollectionSpec.LoadAndAssign.
type profileObjects struct {
	profilePrograms
	profileMaps
	profileVariables
}

func (o *profileObjects) Close() error {
	return _ProfileClose(
		&o.profilePrograms,
		&o.profileMaps,
	)
}

// profileMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProfileObjects or ebpf.CollectionSpec.LoadAndAssign.
type profileMaps struct {
	AgentPidns   *ebpf.Map `ebpf:"agent_pidns"`
	Counts       *ebpf.Map `ebpf:"counts"`
	Stacks       *ebpf.Map `ebpf:"stacks"`
	TargetCgroup *ebpf.Map `ebpf:"target_cgroup"`
}

func (m *profileMaps) Close() error {
	return _ProfileClose(
		m.AgentPidns,
		m.Counts,
		m.Stacks,
		m.TargetCgroup,
	)
}

// profileVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProfileObjects or ebpf.CollectionSpec.LoadAndAssign.
type profileVariables struct {
}

// profilePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProfileObjects or ebpf.CollectionSpec.LoadAndAssign.
type profilePrograms struct {
	HandleSample *ebpf.Program `ebpf:"handle_sample"`
}

func (p *profilePrograms) Close() error {
	return _ProfileClose(
		p.HandleSample,
	)
}

func _ProfileClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed profile_bpfel.o
var _ProfileBytes []byte
